# 임베딩 캐시 설정
embeddings:
  enabled: true  # 캐시 사용 여부
  directory: "embeddings"  # 캐시 저장 디렉토리
  version: "v1"  # 캐시 버전 (설정 변경 시 증가)
  compression: true  # numpy 압축 저장 사용
  metadata:
    save_config: true  # 설정 정보 저장
    save_timestamp: true  # 생성 시간 저장 